\LoadClass[10pt,a4paper,sans]{moderncv}% possible options include font size ('10pt', '11pt' and '12pt'), paper size ('a4paper', 'letterpaper', 'a5paper', 'legalpaper', 'executivepaper' and 'landscape') and font family ('sans' and 'roman')

% moderncv themes
\moderncvstyle{banking}                            % style options are 'casual' (default), 'classic', 'oldstyle' and 'banking'
\moderncvcolor{blue}                                % color options 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'
%\renewcommand{\familydefault}{\sfdefault}         % to set the default font; use '\sfdefault' for the default sans serif font, '\rmdefault' for the default roman one, or any tex font name
%\nopagenumbers{}                                  % uncomment to suppress automatic page numbering for CVs longer than one page


% character encoding
\RequirePackage[utf8]{inputenc}          
\RequirePackage{geometry} % changes margins across the page
 \geometry{
 left=7mm,
 right=7mm,
 top=7mm,
 bottom=7mm,
}
\RequirePackage{amssymb}
\RequirePackage{fontawesome}

\newcommand{\college}{Virginia Tech}

% personal data
%\name{Sergey}{Bashkirov}
%\title{Resumé title}                               % optional, remove / comment the line if not wanted

%\address{1234 1st street}{Novato, california, 94945}{USA}% optional, remove / comment the line if not wanted; the "postcode city" and and "country" arguments can be omitted or provided empty
%\phone[mobile]{+1~(415)~123~4567}                   % optional, remove / comment the line if not wanted
%\email{litedictteam@gmail.com}                               % optional, remove / comment the line if not wanted
%\homepage{ajnorton.com}                         % optional, remove / comment the line if not wanted
%\social[github][github.com/z80]{github.com/z80}
%\social[linkedin][https://www.linkedin.com/in/sergey-bashkirov-52295279] {LinkedIn}
